name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  devsecops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 1. Analyse SAST CodeQL
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Run CodeQL
        uses: github/codeql-action/analyze@v3

      # 2. Analyse sécurité Python avec Bandit
      - name: Run Bandit
        run: |
          pip install bandit
          bandit -r api --severity-level high

      # 3. Scan des dépendances avec Safety
      - name: Dependency Scan
        run: |
          pip install safety
          safety check -r requirements.txt

      # 4. Build Docker
      - name: Build Docker image
        run: docker build -t devsecops-api .

      # 5. Scan Docker avec Trivy
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-api
          format: 'table'
          exit-code: '1' # Fait échouer le pipeline si vulnérabilités
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'